import { Candidate, CandidateSource, KanbanStatus } from './types';

export const CANDIDATES: Candidate[] = [
    {
        id: 1,
        name: 'Aisha Sharma',
        designation: 'Digital Marketing Manager',
        email: 'aisha.sharma@example.com',
        phone: '+971 50 123 4567',
        source: CandidateSource.LINKEDIN,
        aiScore: 9.8,
        status: KanbanStatus.SOURCED,
    },
    {
        id: 2,
        name: 'Ben Carter',
        designation: 'Senior Marketing Specialist',
        email: 'ben.carter@example.com',
        phone: '+971 55 987 6543',
        source: CandidateSource.TIMELESS_DB,
        aiScore: 9.5,
        status: KanbanStatus.SOURCED,
    },
    {
        id: 3,
        name: 'Chloe Davis',
        designation: 'Growth Marketing Head',
        email: 'chloe.davis@example.com',
        phone: '+971 52 876 5432',
        source: CandidateSource.NAUKRI_GULF,
        aiScore: 9.2,
        status: KanbanStatus.SOURCED,
    },
    {
        id: 4,
        name: 'David Rodriguez',
        designation: 'SEO & SEM Expert',
        email: 'david.r@example.com',
        phone: '+971 56 234 5678',
        source: CandidateSource.LINKEDIN,
        aiScore: 9.1,
        status: KanbanStatus.SOURCED,
    },
    {
        id: 5,
        name: 'Emily White',
        designation: 'Content Marketing Lead',
        email: 'emily.white@example.com',
        phone: '+971 50 345 6789',
        source: CandidateSource.TIMELESS_DB,
        aiScore: 8.9,
        status: KanbanStatus.SOURCED,
    },
    {
        id: 6,
        name: 'Fahad Al-Marri',
        designation: 'Digital Marketing Analyst',
        email: 'fahad.almarri@example.com',
        phone: '+971 55 456 7890',
        source: CandidateSource.NAUKRI_GULF,
        aiScore: 7.8,
        status: KanbanStatus.SOURCED,
    },
    {
        id: 7,
        name: 'Grace Lee',
        designation: 'Social Media Manager',
        email: 'grace.lee@example.com',
        phone: '+971 52 567 8901',
        source: CandidateSource.LINKEDIN,
        aiScore: 7.5,
        status: KanbanStatus.SOURCED,
    },
    {
        id: 8,
        name: 'Henry Wilson',
        designation: 'PPC Specialist',
        email: 'henry.wilson@example.com',
        phone: '+971 56 678 9012',
        source: CandidateSource.TIMELESS_DB,
        aiScore: 7.2,
        status: KanbanStatus.SOURCED,
    },
     {
        id: 9,
        name: 'Isabella Garcia',
        designation: 'Marketing Coordinator',
        email: 'isabella.g@example.com',
        phone: '+971 50 789 0123',
        source: CandidateSource.NAUKRI_GULF,
        aiScore: 8.5,
        status: KanbanStatus.SOURCED,
    },
    {
        id: 10,
        name: 'Jamal Khan',
        designation: 'Brand Manager',
        email: 'jamal.khan@example.com',
        phone: '+971 55 890 1234',
        source: CandidateSource.LINKEDIN,
        aiScore: 9.0,
        status: KanbanStatus.SCHEDULED,
    }
];